### ISSUE TITLE
DEAD PROJECT

### ISSUE THREAD

**Issue by DarkBlaez** [meshbird/meshbird#131]
Most likely this is a dead project. Just looking at the website from January 2016, the last update was 8 months ago to a simple file. There have been no responses to issues which address documentation. Typical of a number of projects strengthening across GitHub. Much potential but there are other peering efforts out there that probably have outcompeted this effort.

-DB

**Comment by miolini** [comment]
It's open source. :-)

**Comment by brailateo** [comment]
> But it is a shame there isn't 1 or 2 paragraphs about about how to configure & deploy, It would have really helped anyone even wanting to use Meshbird for tackle updating the code.

I succeeded one year ago to make it work, then something happened and due to lack of activity on the project I switched to something else!
I recommend you three nice projects, actively maintained:
1) Zrok (Geo-scale, next-generation peer-to-peer sharing platform)
2) Pears (unleash the power of P2P)
3) Tailscale (superb private VPN build on wireguard)

Pears use a hypercore library (Javascript) that makes P2P connections and then they build a lot of tools on it ( check hypertele , hyperssh , hypershell , hyperbeam , drives )

Best regards,
Teo

**Comment by bmullan** [comment]
@brailaleo

Thanks for the reply Teo
I had already experimented with Tailscale & it Open Source Controller "Headscale"

I was aware of Zrok but haven't tried it yet.   But at your team's recommendation I'll try to do that sooner than later.

Pears I'd not heard of.

My interest in Open Source Mesh VPN is due to my having spent 20 yrs at Cisco Systems in their Advanced Services
consulting group focused on the Cable MSO's & the Mobile Operators.

I'm retired now but still have a passion for working with these technolgies.

One past project I created a few years ago was this.
**[https://github.com/bmullan/CIAB.Full-Mesh.VPN.Wireguard.FRR.BGP.VXLAN.Internet.Overlay.Architecture](https://github.com/bmullan/CIAB.Full-Mesh.VPN.Wireguard.FRR.BGP.VXLAN.Internet.Overlay.Architecture)**

It worked great.  However, I left programming a long time ago so integrating & configuring it all was primarily
in Bash.

I plan to update it, to utilize the recent **LXD** VM & "_system_" Container Management fork called **Incus**.

If you read through that github link, what I architecturally created was a Layer 2 & 3 Mesh VPN with
BGP providing auto-routing.   It also supported Multicast over the Internet.

Lastly, the use of "system" Containers also _supported a multi-cloud, multi-server, multi-tenant environment_
with LXD (soon Incus) VMs & Containers running almost any Linux Distro.    

_Each "tenant" is isolated from every other "tenant" by use of VxLAN_ as **each "tenant" is assigned a different VxLAN VNID** (**_Virtual Network ID_**).

Since _VxLAN does not support encryption_ I tunnel _all VxLAN traffic through Wireguard from Mesh Node to Mesh Node._

**_BGP  was used for Routing_** to insure unnecessary traffic is **_not_** sent to nodes that don't have any related "tenant" presence on any particular Mesh Node.

Any way...  Meshbird looked interesting because it stated that _Discovery was via IPFS_ but used Wireguard for the
Mesh tunnel connections.   IPFS was an interest to me because I'd used a different application in the past that used
IPFS for Discovery but did not utilize Wireguard so its performance was not the best.

After I read your comment: *I succeeded one year ago to make it work*, then something happened
I may have assumed to much for Meshbird.   But thanks for replying.  

I hope whatever your new projects might be that they are interesting.

Brian

**Comment by brailateo** [comment]
> I'm retired now but still have a passion for working with these technolgies.
> 
> One past project I created a few years ago was this. **https://github.com/bmullan/CIAB.Full-Mesh.VPN.Wireguard.FRR.BGP.VXLAN.Internet.Overlay.Architecture**
> 

Nice work @bmullan ! 
If you will upgrade CIAB with Incus, I am interested in testing it, please let me know somehow about the work in progress ( I'm available on Telegram and GMail with the same username as here ).

BTW, I'm 60 years old and start programming with SFDX , CP/M and 56 Kbytes RAM memory systems! :-) 

Best regards,
Teo
